apiVersion: v1
kind: ServiceAccount
metadata:
  name: insecure-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: insecure-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: insecure-role-binding
subjects:
- kind: ServiceAccount
  name: insecure-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: insecure-role
  apiGroup: rbac.authorization.k8s.io
